checks:
    php: true
build:
    environment:
          php:
            version: '7.4'


    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - phpcs-run

                    -
                        command: composer coverage
                        coverage:
                            file: 'tests/_output/coverage.xml'
                            format: 'clover'
                    - php-scrutinizer-run



tools:
    php_code_coverage: true

filter:
    excluded_paths:
        - 'Examples/'
        - 'tests/'
    dependency_paths:
        - 'vendor/'