checks:
    php: true
build:
    environment:
          php:
            version: '7.4'
            ini:
                'zend_extension': 'xdebug.so'
    nodes:
        tests: false
        analysis:
            tests:
                override:
                    - phpcs-run

                    - php-scrutinizer-run



tools:
    php_code_coverage: false

filter:
    excluded_paths:
        - 'Examples/'
        - 'tests/'
    dependency_paths:
        - 'vendor/'
