checks:
  php: true
build:
  environment:
    php:
            version: '7.4'


  nodes:
    tests: true
    analysis:
      tests:
        override:
          - phpcs-run

          - php-scrutinizer-run



filter:
  excluded_paths:
    - "Examples/"
    - "tests/"
  dependency_paths:
    - "vendor/"
