echo 'public function testFileIterator() { $files =["axislabelbkgex01.php","axislabelbkgex02.php","axislabelbkgex03.php","axislabelbkgex04.php","axislabelbkgex05.php","axislabelbkgex06.php","axislabelbkgex07.php","dupyaxisex1.php","inyaxisex1.php","inyaxisex2.php","inyaxisex3.php","mulyaxisex1.php","topxaxisex1.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/AxisTest.php

echo 'public function testFileIterator() { $files =["background_type_ex0.php","background_type_ex1.php","background_type_ex2.php","background_type_ex3.php","background_type_ex4.php","backgroundex01.php","backgroundex02.php","backgroundex03.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/BackgroundTest.php

echo 'public function testFileIterator() { $files =["accbarex1.php","accbarframeex01.php","accbarframeex02.php","accbarframeex03.php","alphabarex1.php","bar2scalesex1.php","barformatcallbackex1.php","bargradex1.php","bargradex2.php","bargradex3.php","bargradex4.php","bargradex5.php","bargradex6.php","bargradsmallex1.php","bargradsmallex2.php","bargradsmallex3.php","bargradsmallex4.php","bargradsmallex5.php","bargradsmallex6.php","bargradsmallex7.php","bargradsmallex8.php","barimgex1.php","barintex1.php","barintex2.php","barlinealphaex1.php","barlinefreqex1.php","barpatternex1.php","barscalecallbackex1.php","bartutex1.php","bartutex12.php","bartutex2.php","bartutex3.php","bartutex4.php","bartutex5.php","bartutex6.php","grace_ex0.php","grace_ex1.php","grace_ex2.php","grace_ex3.php","groupbarex1.php","horizbarex1.php","horizbarex2.php","horizbarex3.php","horizbarex4.php","horizbarex6.php","logbarex1.php","manual_textscale_ex1.php","manual_textscale_ex2.php","manual_textscale_ex3.php","manual_textscale_ex4.php","negbarvalueex01.php","new_bar1.php","new_bar3.php","new_bar4.php","new_bar6.php","plotbanddensity_ex0.php","plotbanddensity_ex1.php","plotbanddensity_ex2.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/BarTest.php

echo 'public function testFileIterator() { $files =["canvas_jpgarchex.php","canvasbezierex1.php","canvasex01.php","canvasex02.php","canvasex03.php","canvasex04.php","canvasex05.php","canvasex06.php","canvaspiralex1.php","colormaps.php","listfontsex1.php","mkgrad.php","text-example1.php","text-example2.php","textalignex1.php","textpalignex1.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/CanvasTest.php

echo 'public function testFileIterator() { $files =["basic_contourex01.php","basic_contourex02.php","basic_contourex03-1.php","basic_contourex03-2.php","basic_contourex03-3.php","basic_contourex04.php","basic_contourex05.php","contour2_ex1.php","contour2_ex2.php","contour2_ex3.php","contour2_ex4.php","contour2_ex5.php","contour2_ex6.php","contour2_ex7.php","contourex01.php","contourex02.php","contourex03.php","contourex04.php","contourex05.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/ContourTest.php

echo 'public function testFileIterator() { $files =["bar_csimex1.php","bar_csimex2.php","bar_csimex3.php","barcsim_details_omit.php","barcsim_popup.php","barline_csimex1.php","barlinefreq_csimex1.php","boxstockcsimex1.php","csim_in_html_ex1.php","csim_in_html_ex2.php","csim_in_html_graph_ex1.php","csim_in_html_graph_ex2.php","ganttcsimex01.php","ganttcsimex02.php","imgmarkercsimex1.php","matrix_csimex01.php","mulyaxiscsimex1.php","pie3d_csimex1.php","pie_csimex1.php","piec_csimex1.php","polar_csimex1.php","radar_csimex1.php","scatter_csimex1.php","tablebarex1_csim.php","tableex01_csim.php","titlecsimex01.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/CsimTest.php

echo 'public function testFileIterator() { $files =["datamatrix_ex0.php","datamatrix_ex00.php","datamatrix_ex1.php","datamatrix_ex2.php","datamatrix_ex3.php","datamatrix_ex4.php","datamatrix_ex5.php","datamatrix_ex6.php","datamatrix_ex7.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/DatamatrixTest.php

echo 'public function testFileIterator() { $files =["dateaxisex1.php","dateaxisex2.php","dateaxisex3.php","dateaxisex4.php","datescaleticksex01.php","dateutilex01.php","dateutilex02.php","prepaccdata_example.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/DateTest.php

echo 'public function testFileIterator() { $files =["gantt_samerowex1.php","gantt_samerowex2.php","gantt_textex1.php","ganttcolumnfontsex01.php","ganttconstrainex0.php","ganttconstrainex1.php","ganttconstrainex2.php","ganttex00.php","ganttex01.php","ganttex02.php","ganttex03.php","ganttex04.php","ganttex05.php","ganttex06.php","ganttex07.php","ganttex08.php","ganttex09.php","ganttex10.php","ganttex11.php","ganttex12.php","ganttex13-zoom1.php","ganttex13-zoom2.php","ganttex13.php","ganttex14.php","ganttex15.php","ganttex16.php","ganttex17-flag.php","ganttex17.php","ganttex18.php","ganttex19.php","ganttex30.php","ganttex_slice.php","gantthgridex1.php","gantthourex1.php","gantthourminex1.php","gantticonex1.php","ganttmonthyearex1.php","ganttmonthyearex2.php","ganttmonthyearex3.php","ganttmonthyearex4.php","ganttsimpleex1.php","multconstganttex01.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/GanttTest.php

echo 'public function testFileIterator() { $files =["example0-0.php","example0.php","example1.1.php","example1.2.php","example1.php","example10.php","example11.php","example13.php","example14.php","example15.php","example16.1.php","example16.2.php","example16.3.php","example16.4.php","example16.5.php","example16.6.php","example16.php","example17.php","example18.php","example19.1.php","example19.php","example2.1.php","example2.5.php","example2.6.php","example2.php","example20.1.php","example20.2.php","example20.3.php","example20.4.php","example20.5.php","example20.php","example21.php","example22.php","example23.php","example24.php","example25.1.php","example25.2.php","example25.php","example26.1.php","example26.php","example27.1.php","example27.2.php","example27.3.php","example27.php","example28.1.php","example28.2.php","example28.3.php","example28.php","example3.0.1.php","example3.0.2.php","example3.0.3.php","example3.1.1.php","example3.1.php","example3.2.1.php","example3.2.2.php","example3.2.php","example3.3.php","example3.4.1.php","example3.4.php","example3.php","example4.php","example5.1.php","example5.php","example6.1.php","example6.2.php","example6.php","example7.php","example8.1.php","example8.php","example9.1.php","example9.2.php","example9.php","exampleex9.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/GeneralTest.php

echo 'public function testFileIterator() { $files =["bkgimgflagex1.php","bkgimgflagex2.php","bkgimgflagex3.php","bkgimgflagex4.php","bkgimgflagex5.php","imgmarkerex1.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/ImgTest.php

echo 'public function testFileIterator() { $files =["ledex1.php","ledex10.php","ledex11.php","ledex12.php","ledex13.php","ledex14.php","ledex15.php","ledex16.php","ledex17.php","ledex2.php","ledex3.php","ledex4.1.php","ledex4.2.php","ledex4.php","ledex5.php","ledex6.php","ledex7.php","ledex8.php","ledex9.php","ledex_cyrillic.php","ledex_cyrillic2.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/LedTest.php

echo 'public function testFileIterator() { $files =["builtinplotmarksex1.php","centeredlineex01.php","centeredlineex02.php","centeredlineex03.php","centerlinebarex1.php","clipping_ex1.php","clipping_ex2.php","filledgridex1.php","filledline01.php","filledlineex01.1.php","filledlineex01.php","filledlineex02.php","filledlineex03.php","filledstepstyleex1.php","funcex1.php","funcex2.php","funcex3.php","funcex4.php","gradlinefillex1.php","gradlinefillex2.php","gradlinefillex3.php","gradlinefillex4.php","interpolation-growth-log.php","interpolation-growth.php","linebarcentex1.php","linebarex1.php","linebarex2.php","linebarex3.php","linegraceex.php","lineiconex1.php","lineiconex2.php","lineimagefillex1.php","manscaleex1.php","manscaleex2.php","manscaleex3.php","manscaleex4.php","new_line1.php","new_line2.php","new_line3.php","new_line4.php","new_line5.php","new_step1.php","nullvalueex01.php","partiallyfilledlineex1.php","plotlineex1.php","splineex1.php","staticlinebarex1.php","tabtitleex1.php","timestampex01.php","titleex1.php","y2synch.php","y2synch2.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/LineTest.php

echo 'public function testFileIterator() { $files =["matrix_edgeex01.php","matrix_edgeex02.php","matrix_ex0.php","matrix_ex01.php","matrix_ex02.php","matrix_ex03.php","matrix_ex04.1.php","matrix_ex04.2.php","matrix_ex04.php","matrix_ex05.php","matrix_ex06.php","matrix_introex.php","matrix_layout_ex1.php","matrixex00.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/MatrixTest.php

echo 'public function testFileIterator() { $files =["comb90dategraphex01.php","comb90dategraphex02.php","comb90dategraphex03.php","combgraphex1.php","combgraphex2.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/MultigraphTest.php

echo 'public function testFileIterator() { $files =["odoex00.php","odoex01.php","odoex010.php","odoex011.php","odoex012.php","odoex02.php","odoex03.php","odoex04.php","odoex05.php","odoex06.php","odoex07.php","odoex08.php","odoex09.php","odotutex00.php","odotutex01.php","odotutex02.php","odotutex03.php","odotutex04.php","odotutex06.php","odotutex07.php","odotutex08.1.php","odotutex08.php","odotutex09.php","odotutex10.php","odotutex11.php","odotutex12.php","odotutex13.php","odotutex14.php","odotutex15.php","odotutex16.1.php","odotutex16.php","odotutex17.php","odotutex18.php","odotutex19.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/OdometerTest.php

echo 'public function testFileIterator() { $files =["antispamex01.php","linlogex1.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/OtherTest.php

echo 'public function testFileIterator() { $files =["pdf417_ex0.php","pdf417_ex1.php","pdf417_ex1b.php","pdf417_ex1c.php","pdf417_ex2.php","pdf417_ex3.php","pdf417_ex4.php","pdf417_ex5.php","pdf417_ex6.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/PdfTest.php

echo 'public function testFileIterator() { $files =["new_pie1.php","new_pie2.php","new_pie3.php","new_pie4.php","pie3dex1.php","pie3dex2.php","pie3dex3.php","pie3dex4.php","pie3dex5.php","piebkgex1.php","piecex1.php","piecex2.php","pieex1.php","pieex2.php","pieex3.php","pieex4.php","pieex5.php","pieex6.php","pieex7.php","pieex8.php","pieex9.php","pielabelsex1.php","pielabelsex2.php","pielabelsex3.php","pielabelsex4.php","pielabelsex5.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/PieTest.php

echo 'public function testFileIterator() { $files =["polarclockex1.php","polarclockex2.php","polarex0-180.php","polarex0.php","polarex1.php","polarex10.php","polarex2.php","polarex3-lin.php","polarex3.php","polarex4.php","polarex5.php","polarex6.php","polarex7-1.php","polarex7-2.php","polarex7.php","polarex8.php","polarex9.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/PolarTest.php

echo 'public function testFileIterator() { $files =["qr_template.php","qrexample0.php","qrexample00.php","qrexample01.php","qrexample02.php","qrexample03.php","qrexample04.php","qrexample05.php","qrexample06.php","qrexample07.php","qrexample08.php","qrexample09.php","qrexample10.php","qrexample11.php","qrexample12.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/QrTest.php

echo 'public function testFileIterator() { $files =["fixscale_radarex1.php","radarex1.php","radarex2.php","radarex3.php","radarex4.php","radarex5.php","radarex6.1.php","radarex6.php","radarex7.php","radarex8.1.php","radarex8.php","radarex9.php","radarlogex1-aa.php","radarlogex1.php","radarlogex2.php","radarmarkex1.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/RadarTest.php

echo 'public function testFileIterator() { $files =["rotateex1.php","rotex0.php","rotex1.php","rotex2.php","rotex3.php","rotex4.php","rotex5.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/RotateTest.php

echo 'public function testFileIterator() { $files =["balloonex1.php","balloonex2.php","bezierex1.php","ccbp_ex1.php","ccbp_ex2.php","ccbpgraph.class.php","fieldscatterex1.php","footerex1.php","impulsex1.php","impulsex2.php","impulsex3.php","impulsex4.php","loglogex1.php","markflagex1.php","pushpinex1.php","pushpinex2.php","scatterex1.php","scatterex2.php","scatterlinkex1.php","scatterlinkex2.php","scatterlinkex3.php","scatterlinkex4.php","scatterrotex1.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/ScatterTest.php

echo 'public function testFileIterator() { $files =["smallstaticbandsex1.php","smallstaticbandsex10.php","smallstaticbandsex11.php","smallstaticbandsex2.php","smallstaticbandsex3.php","smallstaticbandsex4.php","smallstaticbandsex5.php","smallstaticbandsex6.php","smallstaticbandsex7.php","smallstaticbandsex8.php","smallstaticbandsex9.php","staticbandbarex1.php","staticbandbarex2.php","staticbandbarex3.php","staticbandbarex4.php","staticbandbarex5.php","staticbandbarex6.php","staticbandbarex7.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/StaticbandTest.php

echo 'public function testFileIterator() { $files =["boxstockex1.php","boxstockex2.php","stockex1.php","stockex2.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/StockTest.php

echo 'public function testFileIterator() { $files =["sunspotsex1.php","sunspotsex2.php","sunspotsex3.php","sunspotsex4.php","sunspotsex5.php","sunspotsex6.php","sunspotsex7.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/SunspotTest.php

echo 'public function testFileIterator() { $files =["table_flagex1.php","table_howto1.php","table_howto2.php","table_howto3.php","table_howto4.php","table_howto5.php","table_howto6.php","table_howto7.1.php","table_howto7.2.php","table_howto7.php","table_howto8.php","table_howto9.php","table_mex0.php","table_mex00.php","table_mex1.php","table_mex2.php","table_mex3.php","table_vtext.php","table_vtext_ex1.php","tablebarex1.php","tableex00.php","tableex01.php","tableex02.php","tableex03.php","tableex04.php","tableex05.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/TablesTest.php

echo 'public function testFileIterator() { $files =["aqua_example.php","fusion_example.php","green_example.php","ocean_example.php","orange_example.php","pastel_example.php","rose_example.php","softy_example.php","theme_example.php","universal_example.php","vivid_example.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/ThemeTest.php

echo 'public function testFileIterator() { $files =["manualtickex1.php","manualtickex1a.php","manualtickex2.php","manualtickex3.php","manualtickex4.pp"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/TickTest.php

echo 'public function testFileIterator() { $files =["windrose_2plots_ex1.php","windrose_bgimg_ex1.php","windrose_ex0.php","windrose_ex1.php","windrose_ex1b.php","windrose_ex2.1.php","windrose_ex2.php","windrose_ex3.php","windrose_ex4.php","windrose_ex5.php","windrose_ex6.1.php","windrose_ex6.php","windrose_ex7.1.php","windrose_ex7.php","windrose_ex8.1.php","windrose_ex8.php","windrose_ex9.1.php","windrose_ex9.php","windrose_icon_ex1.php","windrose_layout_ex0.php","windrose_layout_ex1.php"]; foreach($files as $file) { $this->_fileCheck($file);}}} ' >> tests/WindroseTest.php

